### ISSUE TITLE
UUID staus error 404

### ISSUE THREAD

**Issue by Vishnubala95** [AKSW/hawk#24]
Hi when am checking for the status of UUID I get this error.
![screenshot from 2018-03-19 18-05-10](https://user-images.githubusercontent.com/36667048/37595840-34026e82-2ba0-11e8-925e-9ae472e32b82.png)

**Comment by RicardoUsbeck** [comment]
Have you checked the log file?  
Have you configured a correct SPARQL endpoint?
You have not provided  a UUID, e.g. 
http://localhost:8181/status?UUID=00000000-0000-0000-0000-000000000001
