### ISSUE TITLE
Output not so clear

### ISSUE THREAD

**Issue by Vishnubala95** [AKSW/hawk#25]
Hi ,
I could not get a clear output from the question. I have done as per instructions but did not get sparql query,output entities, triples. Please have a look at the screenshot  for your reference.
![screenshot from 2018-03-19 18-08-12](https://user-images.githubusercontent.com/36667048/37596094-06a11654-2ba1-11e8-85ea-26886923eb2f.png)

**Comment by RicardoUsbeck** [comment]
a) Probably the calculation is not finished, have you checked the log file?
b) Your question is not a hybrid question and thus is probably not suited for HAWK.  Try using https://github.com/dice-group/TeBaQA
