### ISSUE TITLE
Build in sophisticated logging

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/hawk#7]
As a developer, I want to see a separate and persistent HAWK log file for all queries and results.

GOAL: The logfile should enable a developer to see a question, its results and which version of HAWK has been used in order to analyse errors in live deployment.

**Comment by dswangGH** [comment]
I want to know the meaning of cardinality of a tree ?(org.aksw.hawk.controller.Cardinality)

**Comment by dswangGH** [comment]
and I found that the opensourced Hawk used http://139.18.2.164:3030/ds/sparql as a sparql engine, I want to know if this engine is also opensourced?thanks.

**Comment by RicardoUsbeck** [comment]
Hi,

cardinality defines the number of answers you expect, e.g., What is the capital of Germany? => 1, How many cities in Germany have a museum? => multiple. The Cardinality class analyses POS tags and tells you whether to expect 1 or multiple results. 

http://139.18.2.164:3030/ds/sparql is a semi-public SPARQL endpoint hosted at our site. The engine is Jena Fuseki with full-text search enabled. You can find a deploy script here: https://github.com/AKSW/NLIWOD/tree/master/qa.hawk/deploy-scripts 

For novel questions or the latest source code please have a look at our new repository at https://github.com/AKSW/NLIWOD

Are there further questions?

**Comment by dswangGH** [comment]
hi,
  thanks for your response, I wander if there some papers or reports related to the uploaded source code NLIWOD, if it has, please give some links,thanks.

**Comment by RicardoUsbeck** [comment]
Hi, have a look here http://aksw.org/Projects/HAWK.html
